apiVersion: v1
kind: Service
metadata:
  name: fashion-service
  labels:
    app: fashion-service
spec:
  selector:
    app: fashion-service
  ports:
  - protocol: TCP
    port: 8100
    targetPort: 8100
#  type: ClusterIP
  type: LoadBalancer
