apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-service
  labels:
    app: fashion-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fashion-service
  template:
    metadata:
      labels:
        app: fashion-service
    spec:
      containers:
      - name: fashion-service
        image: ashokkumarvg/ecommerce-fashion-service:0.0.18-SNAPSHOT
        ports:
        - containerPort: 8100
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_NAME
          value: akfashiondb
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: MYSQL_PASSWORD
          value: "12345678"
        - name: FASHION_SERVICE_HOST
          value: ""
        volumeMounts:
        - name: script-volume2
          mountPath: /scripts
          readOnly: false
        command: ["/bin/sh", "-c"]
        args:
        - |
          chmod +x /scripts/get-external-ip-address.sh
          /scripts/get-external-ip-address.sh java -jar /fashion-service-0.0.18-SNAPSHOT.jar
      restartPolicy: Always
      volumes:
      - name: script-volume2
        configMap:
          name: get-external-ip-script2
          defaultMode: 0755
