apiVersion: v1
kind: ServiceAccount
metadata:
  name: fashion-service-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: fashion-service-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fashion-service-rb
  namespace: default
subjects:
- kind: ServiceAccount
  name: fashion-service-sa
  namespace: default
roleRef:
  kind: Role
  name: fashion-service-role
  apiGroup: rbac.authorization.k8s.io
